version: "3.9"

services:
  # TODO: consider Caddy instead for the reverse proxy
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
    networks:
      - backend

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://root:password@postgresql:5432/test
    volumes:
      - ./:/app
    restart: "unless-stopped"
    networks:
      - backend
    depends_on:
      - postgresql

  postgresql:
    container_name: postgresql
    image: postgis/postgis:17-3.4-alpine # postgres image with postGIS extension
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
  db_data: