# NodeJS Version 18
FROM node:18-alpine

# Work to Dir
WORKDIR /app

COPY ./package.json ./package-lock.json /app/

# Install Node Package
RUN npm install --legacy-peer-deps

# Set Env
ENV NODE_ENV development

# Copy entire dir
COPY . ./app

# Cmd script
CMD ["npm", "run", "prod"]

# TODO: build instead for deployment